import { Geist, Geist_Mono, Azeret_Mono, Quicksand, Cormorant, Ms_Madi } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import MyNavbar from "./components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const azeretMono = Azeret_Mono({
  variable: "--font-azeret-mono",
  subsets: ["latin"],
  weight: ["100"],
});

const quickSand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300"],
});

const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["500"],
});

const msMadi = Ms_Madi({
  variable: "--font-msMadi",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${azeretMono.variable} ${quickSand.variable} ${cormorant.variable} $(msMadi.variable) antialiased`}
      >
      <MyNavbar/>
        {children}
      </body>
    </html>
  );
}
